---
output: 
  pdf_document:
      template: template.tex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\begin{center}
{\Large \textsc{PSTAT 115: Introduction to Bayesian Data Analysis}}
\end{center}
\begin{center}
Fall 2020
\end{center}

\begin{center}
\rule{6in}{0.4pt}
\begin{minipage}[t]{.75\textwidth}
\begin{tabular}{llcccll}
\textbf{Instructor:} & Alexander Franks & & &  & \textbf{Time:} & M/W 11:00-12:15\\
\textbf{Email:} &
                  \href{mailto:afranks@pstat.ucsb.edu}{afranks@pstat.ucsb.edu}
                                        & & & &  & 
\end{tabular}
\end{minipage}
\rule{6in}{0.4pt}
\end{center}
\vspace{.5cm}
\setlength{\unitlength}{1in}
\renewcommand{\arraystretch}{2}


\noindent\textbf{Course Pages:}
\begin{itemize}
\item Link to live lecture: \url{https://ucsb.zoom.us/j/86937803425?pwd=cnNnOUhZWUlkc2ZvN3JWUENiWGVmUT09}
\item Link to section / office hours: \url{ https://ucsb.zoom.us/j/87510865800?pwd=S1FUbUNKYnJOWmFBbHRvRU1sSDZYZz09}
\item Gauchospace: \url{https://gauchospace.ucsb.edu/courses/mod/forum/view.php?id=4471455}
\item Piazza: \url{piazza.com/ucsb/fall2020/pstat115}
\item pstat115.lsit.ucsb.edu: Use \url{https://bit.ly/32cO6dm} to sync new assignments and labs.  
\begin{itemize}
\item Bookmark this link, you will use it alot!
\end{itemize}
\end{itemize}



\vskip.15in
\noindent\textbf{Office Hours:}

\noindent Professor Franks: \url{afranks@pstat.ucsb.edu} Office Hours, Wednesday 2pm

\noindent Xubo Liu \url{xubo@ucsb.edu}: Office Hours TBD

\noindent Dorothy Li \url{dorothyli@pstat.ucsb.edu}: Office Hours TBD

\vskip.15in
\noindent\textbf{Course Texts} 

\begin{itemize}
\item \textbf{Required:} Peter Hoff {\textit{A First Course in Bayesian
      Statistical Methods}};  \url{https://www.springer.com/us/book/9780387922997}). (pdf available on the course website)
\item Optional: Jim Albert {\textit{Bayesian Computation with R}};
  \url{https://www.springer.com/us/book/9780387922973}).
  \item Optional: Richard McElreath {\textit{Statistical Rethinking}};  \url{https://xcelab.net/rm/statistical-rethinking/}).  
  \item Optional: Andrew Gelman, John Carlin et al. {\textit{Bayesian
        Data Analysis}};  \url{http://www.stat.columbia.edu/~gelman/book/}).
\end{itemize} 

\vskip.15in
\noindent\textbf{Objectives:} 

\vspace{1em}
At the end of the course, a successful student will be able to:
\begin{itemize}
\item build and refine statistical models using the Bayesian paradigm
\item utilize Monte Carlo methods for statistical inference
\end{itemize}

\vskip.15in
\noindent\textbf{Prerequisites:}
PSTAT 120 A-B (probability and math-stat) and 126 (regression). Familiarity with R is required.

\vspace*{.15in}

\noindent \textbf{Tentative Course Topics:}
\begin{center}
\begin{minipage}{5in}
\begin{flushleft}
{\color{darkgreen}{\Rectangle}} ~ Review of frequentist inference\\
{\color{darkgreen}{\Rectangle}} ~ One parameter models\\
{\color{darkgreen}{\Rectangle}} ~ Monte Carlo computation\\
{\color{darkgreen}{\Rectangle}} ~ The normal model\\
{\color{darkgreen}{\Rectangle}} ~ Markov chain Monte Carlo\\
{\color{darkgreen}{\Rectangle}} ~ Hierarchical models\\
\end{flushleft}
\end{minipage}
\end{center}

\pagebreak

\vspace*{.15in}
\noindent\textbf{Grading Policy:}
\begin{itemize}
\item Homework (30\%).
  \begin{itemize}
    \item There will be approximately 6 homeworks, due roughly every
     week on Sundays at midnight.\\
      \item You are allowed to work with a partner. You need only turn in one homework per pair.  If you need help finding a partner, start with the ``Search for
  Teammates'' tool on Piazza.  Homework solutions must be done in
  RMarkdown and turned in on Gradescope.  Each homework assignment will be given as a
  template that you should work from.\\
\item All code must be written to be reproducible in Rmarkdown
\item  All derivations can be done in any format of your choosing (latex, written by hand) but must be legible and \emph{must be incorporated into your final pdf}.
\item  All files must be zipped together and submitted to Gradescope
\item  Ask a TA \emph{early} if you have problems regarding submissions. 
  \item Homework not submitted online before the deadline will
  be considered late (10 point deduction). 24 hours after the deadline
  homework will not be accepted and no credit will be awarded. Do not
  wait until the night before it is due to start working!
  \end{itemize}

\item Midterm exam (20\%). \textbf{Take home, due November 9, 2020} . 
\item 10\% quizzes
  \begin{itemize}
    \item Approximately 5 in quizzes (online), lowest dropped
     \item There is no make-up for missed quizzes.
    \end{itemize}
\item Section attendance (10\%)
  \begin{itemize}
    \item Section attendance is required and essential.  Your
    attendance will be noted.  
    \end{itemize}
\item Final exam (30\%). \textbf{Take home, due Monday December 16, 2020}
\end{itemize}

\noindent{\textbf{Homeworks:}}

\begin{itemize}
\item  All files will be submitted electronically via Gradescope
\item  Submit a zip file containing:
  \begin{enumerate}
    \item R markdown code (.Rmd file, template provided)\\
    \item Any additional files as needed\\
    \item Generated PDF file
  \end{enumerate}
\end{itemize}
\vskip.15in
\noindent\textbf{Important Dates:}
\begin{center} \begin{minipage}{3.8in}
    \begin{flushleft}
Midterm \dotfill ~  November 9, 2020 (take home)\\
Final Exam \dotfill ~ December 16, 2020 (take home)\\
\end{flushleft}
\end{minipage}
\end{center}

\vskip.15in
\noindent\textbf{Course Policies:}  
\begin{itemize}
\item Please sign up for Piazza: \url{piazza.com/ucsb/fall2020/pstat115}.  All questions related to course content, homework, R programming and quizzes should be done on Piazza. \textit{Only questions pertaining to grades or personal issues should be handled over email}.
\item Regular attendance is strongly encouraged and can count toward you participationg grade!
\end{itemize}